### ISSUE TITLE
Comprehensive fix of misspellings/typos

### ISSUE THREAD

**Issue by josefpihrt** [peachpiecompiler/peachpie-docs#7]
Hi,

I would like to contribute with a comprehensive fix of misspellings/typos in this project.

I developed tools specially for this purpose: Orang (CLI tool) and Wordb (wordlists).

#### Questions

* Are you interested?
* Should US or British (or both) English be preferred?

**Comment by josefpihrt** [comment]
@jakubmisek Why didn't you just ask me to remove the [links](https://github.com/peachpiecompiler/peachpie/issues/966) if you consider them to be improper. Instead you shut me down like if I commit some kind of an offense. That's rude.

**Comment by jakubmisek** [comment]
duplicate https://github.com/peachpiecompiler/peachpie/issues/966
